### ISSUE TITLE
下载图片可以是原图模式下载吗？目前运行都是压缩过的

### ISSUE THREAD

**Issue by iwwz** [1061700625/QQZone_AutoDownload_Album#3]

**Comment by lang07123** [comment]
需要进行简单的修改：
`       
img_rel = img_ori.replace(r'/m/', r'/o/').replace(r'psbe?', r'psb?').replace(r'/mnull', r'/b')
img_rel = img_rel.replace(r'/m&', r'/b&').replace(r'rf=photolist', r'rf=viewer_4&save=1&d=1')
img_rel = img_rel.replace(r"&t=5",r"")
img_rel = re.sub(r"//\w*.photo.store.qq.com",r"//r.photo.store.qq.com", img_rel)
`

然后在下载的位置判断一下：

`       
        img_html = requests.get(img_rel, timeout=60)
        if img_html.status_code == 200:
            f = open(str(fileName) + '.jpg', 'wb')  # 写入多媒体文件必须要 b 这个参数！
            f.write(img_html.content)  # 多媒体文件是用conctent！
            f.close()
            if imghdr.what(str(fileName) + '.jpg') == 'webp':
                print("* webp格式图片 *")
                os.rename(str(fileName)+'.jpg', str(fileName)+'.webp')
                webpTojpg(str(fileName)+'.webp')
        else:
            img_rel = img_ori.replace(r'/m/', r'/b/').replace(r'psbe?', r'psb?').replace(r'/mnull', r'/b').replace(r'/m&', r'/b&').replace(r'rf=photolist', r'rf=viewer_4')
            img_html = requests.get(img_rel, timeout=60)
            f = open(str(fileName) + '.jpg', 'wb')  # 写入多媒体文件必须要 b 这个参数！
            f.write(img_html.content)  # 多媒体文件是用conctent！
            f.close()
            if imghdr.what(str(fileName) + '.jpg') == 'webp':
                print("* webp格式图片 *")
                os.rename(str(fileName)+'.jpg', str(fileName)+'.webp')
                webpTojpg(str(fileName)+'.webp')`

不知道能不是能解决你的问题。。反正我的问题解决了。。。有一些原图并没有暴露出来。。需要通过另外的连接才可以下载。。但是我不知道那些有原图。。懒的翻JS调用，直接没有原图就下载那个展示图就行了
