### ISSUE TITLE
我的相册会出现无法全部下载的情况

### ISSUE THREAD

**Issue by lang07123** [1061700625/QQZone_AutoDownload_Album#5]
我修改了一些代码：
`
        while True:
            album_list = driver.find_elements_by_css_selector('.c-tx2.js-album-desc-a')[which_album]
            print('进入相册中...', album_list.get_attribute('title'))
            album_list.click()
            time.sleep(5)

            #driver.find_element_by_class_name('pic-num-wrap')

            win_height_before_scroll = driver.get_window_size()['height']

            driver.switch_to.default_content()
            length = length + 100
            js = "var q=document.documentElement.scrollTop=" + str(500 + length)
            driver.execute_script(js)
            time.sleep(3)
            driver.switch_to.frame('tphoto')
            time.sleep(2)

            if win_height_before_scroll == driver.get_window_size()['height']:
                print("已经翻到最底部... 开始下载")
                break
            else:
                print("没翻页到底部... 继续翻页")
                continue
`
逻辑是一个劲的向下翻页，直到页面高度不再变更。就开始下载

**Comment by lang07123** [comment]
> 
> 
> 我修改了一些代码：
> `
> while True:
> album_list = driver.find_elements_by_css_selector('.c-tx2.js-album-desc-a')[which_album]
> print('进入相册中...', album_list.get_attribute('title'))
> album_list.click()
> time.sleep(5)
> 
> ```
>         #driver.find_element_by_class_name('pic-num-wrap')
> 
>         win_height_before_scroll = driver.get_window_size()['height']
> 
>         driver.switch_to.default_content()
>         length = length + 100
>         js = "var q=document.documentElement.scrollTop=" + str(500 + length)
>         driver.execute_script(js)
>         time.sleep(3)
>         driver.switch_to.frame('tphoto')
>         time.sleep(2)
> 
>         if win_height_before_scroll == driver.get_window_size()['height']:
>             print("已经翻到最底部... 开始下载")
>             break
>         else:
>             print("没翻页到底部... 继续翻页")
>             continue
> ```
> 
> `
> 逻辑是一个劲的向下翻页，直到页面高度不再变更。就开始下载

好像并不是这里解决的。。但是无所谓了哈哈哈哈哈。

**Comment by 1061700625** [comment]
已修复
